mopen: mopen.o
	gcc -o mopen mopen.o

mopen.o: mopen.c
	gcc -c mopen.c

try_pthreads2: try_pthreads2.o
	gcc -o try_pthreads2 -pthread try_pthreads2.o

try_pthreads2.o: try_pthreads2.c
	gcc -c -pthread try_pthreads2.c

try_pthreads3: try_pthreads3.o
	gcc -o try_pthreads3 -pthread try_pthreads3.o

try_pthreads3.o: try_pthreads3.c
	gcc -c -pthread try_pthreads3.c

try_pthreads4: try_pthreads4.o
	gcc -o try_pthreads4 -pthread try_pthreads4.o

try_pthreads4.o: try_pthreads4.c
	gcc -c -pthread try_pthreads4.c
